# Generated by Django 3.1.1 on 2020-09-08 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200908_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publishing_date',
            new_name='timestamp',
        ),
    ]
