# Generated by Django 3.1.1 on 2020-09-09 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='featured',
            new_name='slider_post',
        ),
    ]
