# Generated by Django 3.1.1 on 2020-09-09 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20200909_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slider_post',
        ),
    ]
