# Generated by Django 3.1.1 on 2020-09-13 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
